// function to generate markdown for README
function generateMarkdown(data) {

  // Initialise an empty array[] to store our formatted string
  let answers = [];

  // Initialise an array[] to create a markdown table of contents section
  // We will inject this into the answers[] array at position [2] - which is after the description.
  let contents = "## Table of Contents\n";

  // A custom flag used when creating the questions section of the README.md
  let questionsHeadingExists = false;


  // Loop through each of the answers to format the README.md contents based on the content.
  // i.e. If the user has not answered various questions, that corresponding section will not 
  // be added to the string returned.

  // Use a for in loop to iterate through the answers object generated by the inquirer module {}
  for (const key in data) {

    // Switch statement to format our README.md based on inquirer object{} key
    switch (key) {
      case "title":
        if (data[key] !== "") {
          // Push string to array
          answers.push(`# ${data[key]}\n`);
        }
        break;
      case "description":
        if (data[key] !== "") {

          let string = "";
          string += `## Description\n${data[key]}\n`;
          answers.push(string);
          
        };
        break;
      case "installation":
        if (data[key] !== "") {

          let string = "";
          string += `## Installation\n${data[key]}\n`;
          answers.push(string);

          contents+= "[Installation](#installation)<br>\n";
        };
        break;
      case "usage":
        if (data[key] !== "") {

          let string = "";
          string += `## Usage\n${data[key]}\n`;
          answers.push(string);

          contents+= "[Usage](#usage)<br>\n";
        };
        break;
      case "license":
        if (data[key] !== "") {

          let string = "";
          string += `## License\n`
          string += `This app uses the following license: ${data[key]}\n`;
          answers.push(string);          
      
          contents+= "[License](#license)<br>\n";
        };
        break;
      case "contributing":
        if (data[key] !== "") {

          let string = "";
          string += `## Contributing\n${data[key]}\n`;
          string += ``
          answers.push(string);

          contents+= "[Contributing](#contributing)<br>\n";
        };
        break;
      case "tests":
        if (data[key] !== "") {

          let string = "";
          string += `## Tests\n${data[key]}\n`;
          string += ``
          answers.push(string);

          contents+= "[Tests](#tests)<br>\n";
        };
        break;
      case "github":
        if (data[key] !== "") {

          let string = "";
          string += `## Questions\n`
          string += `If you have any questions or would like to get in touch, please see my contact details below.\n`;
          string += `GitHub: [${data[key]}](https://github.com/${data[key]})<br>\n`;
          answers.push(string);


          contents+= "[Questions](#questions)<br>\n";

          questionsHeadingExists = true;
        };
        break;
      case "email":
        if (data[key] !== "") {
          let string = "";
          if(!questionsHeadingExists) {
            string += `## Questions\n`;
            string += `If you have any questions or would like to get in touch, please see my contact details below.\n`;
            contents+= "[Questions](#questions)<br>\n";
          }
          string += `Email: [${data[key]}](mailto:${data[key]})<br>\n`;
          answers.push(string);
          
        };
        break;
    }
  }
  return answers.splice(2,0,contents).join("");



  // console.log(data)
  //   const {
  //     title,
  //     description,
  //     installation,
  //     usage,
  //     license,
  //     contributing,
  //     tests,
  //     github,
  //     email
  //   } = data;

  //   return `

  // # ${title} ${getLicenseBadge(license)}

  // ## Description
  // ${description}

  // ### Table of Contents
  // [Installation](#installation)<br>
  // [Usage](#usage)<br>
  // [License](#license)<br>
  // [Contributing](#contributing)<br>
  // [Tests](#tests)<br>
  // [Questions](#questions)<br>

  // ## Installation
  // ${installation}

  // ## Usage
  // ${usage}

  // ## License
  // This app uses the following license: ${license}

  // ## Contributing
  // ${contributing}

  // ## Tests
  // ${tests}

  // ## Questions

  // If you have any questions or would like to get in touch, please see my contact details below.

  // Github profile: [${github}](https://github.com/${github})

  // Email address: [${email}](mailto:${email})
  // `;
}

// a function to get a license badge
function getLicenseBadge(license) {

  let badge = "";

  switch (license) {
    case "Apache License 2.0":
      badge = "![license](https://img.shields.io/badge/license-Apache%202.0-blue)";
      break;

    case "MIT License":
      badge = "![license](https://img.shields.io/badge/license-MIT-blue)";
      break;

    case "GNU General Public License v3.0":
      badge = "![license](https://img.shields.io/badge/license-GNU%203.0-blue)";
      break;

    case "Mozilla Public License 2.0":
      badge = "![license](https://img.shields.io/badge/license-Mozilla%202.0-blue)";
      break;

    default:
      badge = "";
  }

  // Return the badge markdown code
  return badge;
}

module.exports = generateMarkdown;